### ISSUE TITLE
Import parameters into the filters, economics & weights 

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#50]
Simular to the button added to export 3 files representing the filters, economics & weights of the app's parameters: 
![export-parameters](https://user-images.githubusercontent.com/29183781/226778008-9dc43b58-30d9-4a93-8d82-b861a14897dc.png)
We need to add a new button to do the reverse operation and import these files.
The button should ideally be to the side (left or right) of the existing export button and work with the selection of multiple files or one file at the time.
The app should only accept files that are with the same file name as the exported files (Maybe we should account for the default extension of duplicate files too?).

**Comment by timlinux** [comment]
Also the download / upload buttons should be side by side:

![imagem](https://user-images.githubusercontent.com/178003/227156938-590fe9fa-1f92-4a56-8816-41add641fbcf.png)


@ClaraIV ok for you if we label them as per my mockup above?

**Comment by akshay2408** [comment]
#51

**Comment by ClaraIV** [comment]
yes, but Export / Import :) Let's try to make them take as least space as possible, while looking in-line with the rest of the interface there

**Comment by ClaraIV** [comment]
@akshay2408 we discussed with Belgacem the following (I am not sure if he already created tickets for this):
- the list of parameters to be exported must match the list of parameters displayed for a certain technology -> what you see is what you get; we cannot have anchorages as parameter listed for Solar or Onshore Wind
- the order of the items in the CSV must match the order of the data layers in the parameters list

![image](https://user-images.githubusercontent.com/9391517/234326497-0d332018-5316-4ef1-9ab8-0d899cb96691.png)

**Comment by akshay2408** [comment]
Hi @ClaraIV 
this is done, but not deployed on staging. So moving it to done section.

**Comment by ClaraIV** [comment]
@akshay2408  you mean that my comments above was addressed? Ok, grateful if you could test it internally several times before moving it to "Passed Internal Testing"

**Comment by akshay2408** [comment]
@ClaraIV Okay

**Comment by ClaraIV** [comment]
@MarinaKartoza @akshay2408 I am not sure how the internal testing is performed, but this ticket has not been resolved.
I cannot import the CSVs back into the tool, I get an "invalid file" error even though I am using the exact same file I just downloaded

![image](https://user-images.githubusercontent.com/9391517/236502037-ec226ebd-0adb-417d-b5ea-a5ecd0be586f.png)

**Comment by dimasciput** [comment]
@ClaraIV this is fixed, please give it another try.

**Comment by dimasciput** [comment]
@akshay2408 can you test this ticket please.

**Comment by akshay2408** [comment]
@dimasciput  I have tested the above changes, working fine and able to import csv file

**Comment by LunaAsefaw** [comment]
@dimasciput @akshay2408 for some odd reason, the error message regarding the csv shows for a split second then disappears.

**Comment by LunaAsefaw** [comment]
@dimasciput @akshay2408 This currently fails fortwo reasons:
1. When I import a csv file, I still get the error message showing every single time but for a split second then nothing happens, the values in the filters are the default values or previous values but they're not the values found I the imported csv.
2. When user selects a country, a resource and zone type and chooses to import a csv for the filters, the platform should not reset. Currently after the user selects the country, resource, zone type and imports a csv, the system resets and the user is required to input the values again (then again, which becomes an endless loop).

**Comment by gclapp1** [comment]
Reviewed for multiple countries, resources, zone types and parameters-all worked. Accordingly closing this ticket, #51 and #52.
